FROM gradle:4.10.2-jdk8

RUN     mkdir           app
COPY    src             app
COPY    gradle          app
COPY    build.gradle    app
COPY    settings.gradle app

WORKDIR app

ARG BROWSERSTACK_USERNAME
ARG BROWSERSTACK_ACCESS_KEY
ARG GEB_BROWSERSTACK_PROJECT

ENV BROWSERSTACK_USERNAME=$BROWSERSTACK_USERNAME
ENV BROWSERSTACK_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY
ENV GEB_BROWSERSTACK_PROJECT=$GEB_BROWSERSTACK_PROJECT

RUN gradle clean assemble